pipeline {
    agent any

    environment {
        TF_WORKSPACE = "infra.dev"
        TF_PLAN_FILE = "tfplan.out"
    }

    stages {
        stage('Terraform Init') {
            steps {
                dir("backend/infra.dev") {
                    sh 'ls -al'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir("backend/infra.dev") {
                    sh "terraform plan -out=${TF_PLAN_FILE} -var-file=../properties.json"
                }
            }
        }

        stage('Approve Plan') {
            steps {
                input message: 'Do you voulez appliquer ce plan Terraform ?'
            }
        }

        // stage('Terraform Apply') {
        //     steps {
        //         dir("${TF_WORKSPACE}") {
        //             sh "terraform apply ${TF_PLAN_FILE}"
        //         }
        //     }
        // }
    }
}