pipeline {
    agent any

    environment {
        TF_WORKSPACE = "infra.dev"
        TF_PLAN_FILE = "tfplan.out"
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION="eu-west-3"
        AWS_REGION="eu-west-3"
        JWT_SECRET = credentials('JWT_SECRET')
        MAILGUN_KEY = credentials('MAILGUN_KEY')
    }


    stages {
        stage('Terraform Init') {
            steps {
                dir("backend/infra.dev") {
                    sh '''
                    export TF_WORKSPACE=dev
                    terraform init -no-color -reconfigure -input=false
                    '''
                }
            }
        }

        stage('Install lambdas dependencies') {
            steps {
                dir("backend/lambdas") {
                    sh "./install.sh"
                }
            }
        }

        stage('Build lambdas') {
            steps {
                dir("backend/lambdas") {
                    sh "./build.sh"
                }
            }
        }

        stage('Generate tfvars') {
            steps {
                dir("backend/infra.dev") {
                    sh '''
                    echo "JWT_SECRET = \\"$JWT_SECRET\\"" > terraform.tfvars
                    echo "MAILGUN_KEY = \\"$MAILGUN_KEY\\"" >> terraform.tfvars
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir("backend/infra.dev") {
                    sh '''
                    export TF_WORKSPACE=dev
                    terraform plan -no-color -out=${TF_PLAN_FILE} -var-file=../properties.json
                    '''
                }
            }
        }

        stage('Terraform json changes') {
            steps {
                dir("backend/infra.dev") {
                    sh '''
                    bash -c '
                    secrets=("${JWT_SECRET}" "${MAILGUN_KEY}")
                    terraform show -json ${TF_PLAN_FILE} | sed -f <(for s in "${secrets[@]}"; do echo "s/$s/*******/g"; done) > tfplan.json
                    sed -e "/INSERT_PLAN/r tfplan.json" -e "/INSERT_PLAN/d" ../terraform-changes.html > terraform-changes.html
                    '
                    '''
                    // archiveArtifacts artifacts: 'terraform-changes.html', fingerprint: true
                }
            }
        }
        stage('Publish Plan') {
            steps {
                dir("backend/infra.dev") {
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: '.',
                        reportFiles: 'terraform-changes.html',
                        reportName: 'Terraform Plan Viewer'
                    ])
                }
            }
        }


        stage('Approve Plan') {
            steps {
                script {
                    input message: "Voulez-vous appliquer ce plan ?"
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir("backend/infra.dev") {
                    sh '''
                        export TF_WORKSPACE=dev
                        terraform apply -auto-approve tfplan.out -no-color
                    '''
                }
            }
        }
    }
}