pipeline {
    agent any

    environment {
        TF_WORKSPACE = "${params.STAGE}"
        TF_PLAN_FILE = "tfplan.out"
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION="eu-west-3"
        AWS_REGION="eu-west-3"
        JWT_SECRET = credentials('JWT_SECRET')
        MAILGUN_KEY = credentials('MAILGUN_KEY')
        STAGE = "${params.STAGE}"
        AWS_ACCOUNT_ID = "${params.AWS_ACCOUNT_ID}"
    }


    stages {
        stage('Terraform Init') {
            steps {
                dir("backend/infra") {
                    sh '''
                    terraform init -no-color -reconfigure -input=false
                    '''
                }
            }
        }

        stage('Edit properties') {
            steps {
                dir("backend") {
                    sh '''
                    cat properties.json > tmp.json &&  jq --arg s "${STAGE}" --arg a "${AWS_ACCOUNT_ID}" '.STAGE=$s | .AWS_ACCOUNT_ID=$a' tmp.json > properties.json
                    '''
                }
            }
        }


        stage('Install lambdas dependencies') {
            steps {
                dir("backend/lambdas") {
                    sh "./install.sh"
                }
            }
        }

        stage('Build lambdas') {
            steps {
                dir("backend/lambdas") {
                    sh "./build.sh"
                }
            }
        }

        stage('Generate tfvars') {
            steps {
                dir("backend/infra") {
                    sh '''
                    echo "JWT_SECRET = \\"$JWT_SECRET\\"" > terraform.tfvars
                    echo "MAILGUN_KEY = \\"$MAILGUN_KEY\\"" >> terraform.tfvars
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir("backend/infra") {
                    sh '''
                    terraform plan -no-color -out=${TF_PLAN_FILE} -var-file=../properties.json
                    '''
                }
            }
        }

        stage('Approve Plan') {
            steps {
                script {
                    input message: "Voulez-vous appliquer ce plan ?"
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir("backend/infra") {
                    sh '''
                        terraform apply -auto-approve tfplan.out -no-color
                    '''
                }
            }
        }
    }
}